name: PushToProd
on:
  push:
    branches:    
      - master 
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout
      uses: actions/checkout@master

    - name: Docker Registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 

    # Build the Docker images
    - name: Build Docker Images 
      run: |        
        $GITHUB_WORKSPACE/builder/docker-build.sh

    # Push the Docker images
    - name: Push Docker Images 
      run: |        
        $GITHUB_WORKSPACE/builder/docker-push.sh

      # this action will save the kubeconfig file to `/github/workspace/.kube/config`, which is visible to subsequent steps.
    - name: Get kubeconfig file from GKE
      uses: machine-learning-apps/gke-kubeconfig@master
      with:
        application_credentials: ${{ secrets.APPLICATION_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}
        location_zone: ${{ secrets.LOCATION_ZONE }}
        cluster_name: ${{ secrets.CLUSTER_NAME }}
  
    - name: Test kubectl - get pods
      run: kubectl --kubeconfig=.kube/config get pods
    
    # Update Deployment Configs
    - name: Update Deployment Configs For Services
      run: |        
        $GITHUB_WORKSPACE/builder/deploy-update.sh
  
    # Roll Out Deployment Configs
    - name: Roll Out Deployment Configs
      run: |        
        $GITHUB_WORKSPACE/builder/run-deployments.sh

 #   # Roll Out Deployment Configs
 #   - name: Roll Out Deployment Status
 #     run: |        
 #       $GITHUB_WORKSPACE/builder/rollout-status.sh